# Generated by Django 2.0 on 2022-11-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_curd', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
