# Generated by Django 2.0 on 2022-11-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_curd', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obj',
            name='brithday',
            field=models.DateField(),
        ),
    ]
